repos:
  - repo: local
    hooks:
      - id: bazel-mod-tidy
        name: bazel mod tidy
        language: system
        entry: bazel mod tidy
        pass_filenames: false
        files: go\.(mod|work|sum)$

      - id: gazelle
        name: gazelle
        language: system
        entry: bazel run //:gazelle
        pass_filenames: false
        files: \.go$

      - id: check-secrets-dir
        name: check secrets directory
        language: python
        entry: python meta/scripts/check_secrets_dir.py
        pass_filenames: true
        files: ^secrets/
