name: Setup Bazel with remote cache
description: Installs Bazel via Bazelisk and configures the Buildbuddy remote cache.

inputs:
  buildbuddy-api-key:
    description: Buildbuddy API key for remote cache authentication
    required: true

runs:
  using: composite
  steps:
    - uses: bazel-contrib/setup-bazel@0.19.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
    - run: echo "common:remote --remote_header=x-buildbuddy-api-key=${{ inputs.buildbuddy-api-key }}" >> .bazelrc.user
      shell: bash
