name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gazelle-check:
    name: Gazelle check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - run: bazel run //:gazelle -- -mode=diff

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    needs: gazelle-check
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - run: bazel test //...
